
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: athjihan/digital-menu:latest
    ports:
      - "5500:5500"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: ""
      DB_NAME: seafood_database
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    build:
      context: ./custom-mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: seafood_database
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      start_period: 30s

volumes:
  db_data:
